Simple authentication
spbu-math-cs-mse/edu-platform pull request #22
Opened 2024-12-04 03:27 UTC by RSMT98

2024-12-04 07:07 UTC, metametamoon requested changes
Нужно поправить. Я написал проблемы в одном месте, нужно их исправить сразу во всех. Если что-то непонятно, обращайся.

2024-12-04 07:07 UTC, metametamoon commented on admin-bot/src/main/kotlin/states/StartState.kt
> +        val id = waitTextMessage().first().content.text.toLongOrNull()?.let { userIdRegistry.getUserId(UserId(RawChatId(it))) }
Мы должна вводить именно желаемый StudentId, не tgId. Т.е. мы вообще не хотим обращаться к registry здесь и в аналогичных местах.

2024-12-04 07:07 UTC, metametamoon commented on admin-bot/src/main/kotlin/states/StartState.kt
> +fun DefaultBehaviourContextWithFSM<BotState>.strictlyOnStartState(userIdRegistry: AdminIdRegistry, isDeveloperRun: Boolean = false) {
Не надо называть как `userIdRegistry` переменную типа `AdminIdRegistry`, это сбивает с толку

2024-12-04 07:07 UTC, metametamoon commented on admin-bot/src/main/kotlin/states/StartState.kt
> +        val id = waitTextMessage().first().content.text.toLongOrNull()?.let { userIdRegistry.getUserId(UserId(RawChatId(it))) }
При этом если пользователь ввел не число, надо явно вывести, что ожидается именно число, для упрощения дебага же. 
Осмысленно выводить предупреждение, если такого студента нет (см. `StudentStorage`).

2024-12-04 16:15 UTC, RSMT98 commented
Поменял всё и сделал всё как надо.
Из особенностей: сам сделал `ParentStorage` по аналогии с другими storage, но так как `DatabaseParentStorage` пока не существует, в `main` в `parent-bot` сейчас просто подаётся `TODO()` xD
Ещё откатил все сделанные изменения с `admin-bot`. Сначала хотел тоже сделать по аналогии класс `AdminStorage`, но потом понял, что у нас нет класса `Admin`, который этот storage мог бы ресолвить... ну и вот :)

2024-12-05 06:27 UTC, metametamoon approved these changes
:fire:

2024-12-05 16:01 UTC, metametamoon requested changes
Это не аутентификация, если id потом нигде не используется

2024-12-05 19:45 UTC, metametamoon commented on teacher-bot/src/main/kotlin/states/StartState.kt
> +      // TODO: put teacherId into teacherIdRegistry
Эти и прочие todo-шки надо убрать

2024-12-06 10:03 UTC, metametamoon approved these changes

2024-12-06 10:03 UTC, metametamoon commented
Отлично!

2024-12-06 10:49 UTC, merged