Admin bot
spbu-math-cs-mse/edu-platform pull request #7
Opened 2024-10-29 08:04 UTC by annapiatkova

Умеет создавать новые курсы и редактировать уже существующие: добавлять/убирать учеников и преподавателей, изменять описание курса

Workflow падает из-за spotless, хотя я скачала плагин, который применяет spotless, и применила ко всем файлам. Кажется, ему не нравятся newline как \r\n, но это не точно

2024-10-29 15:47 UTC, Nosorozhek requested changes
Нужно исправить нижеизложенные баги, разбить код на файлы и постараться вынести клавиатуры в отдельные методы, чтобы они не путались с основной бизнес-логикой.

Из субъективных замечаний, я бы оспорил использование reply keyboard для выбора курсов из списка, кажется, будет удобнее, если клавиатура будет inline и отображаться прямо под сообщением. 

В идеале добавить удаление предыдущих сообщений, когда они становятся неактуальны, например, как это сделано в [student-bot](https://github.com/spbu-math-cs-mse/edu-platform/pull/6) и отображение всех доступных для удаления с курса учеников списком, ну или хотя бы опцию просмотра всех учеников/преподавателей на курсе.

2024-10-29 15:47 UTC, Nosorozhek commented on admin-bot/src/main/kotlin/Main.kt
> +            +"Введите новое описание курса ${state.course}. Текущее описание:" + newLine + newLine
Здесь нужно изменить `state.course` на название курса, сейчас название курса выводится некорректно.

2024-10-29 15:47 UTC, Nosorozhek commented on admin-bot/src/main/kotlin/Main.kt
> +
В этот момент нужно удалять reply keyboard, потому что курс уже выбран и она не нужна.

2024-10-29 15:47 UTC, Nosorozhek commented on admin-bot/src/main/kotlin/Main.kt
> +          MenuState(state.context)
Здесь после получения команды `/stop` и перехода в `MenuState`, бот зависает (с точки зрения пользователя) и его не спасает даже команда `/start`.

2024-11-10 14:52 UTC, buyolitsez commented on admin-bot/build.gradle.kts
> +    mainClass.set("com.github.heheteam.samplebot.MainKt")
adminbot

2024-11-10 14:52 UTC, buyolitsez commented on admin-bot/src/test/kotlin/SampleTest.kt
> +import kotlin.test.Test
лучше удалить наверное этот файл

2024-11-16 00:06 UTC, merged